### ISSUE TITLE
Unable to build with recent Vulkan-Headers

### ISSUE THREAD

**Issue by dj2** [KhronosGroup/Vulkan-Headers#111]
If you have the latest Vulkan-Headers and you use it by adding the headers subdirectory first the configure step will fail. This is due to KhronosGroup/Vulkan-Headers@382bf3d which changed the target_include_directories command to have the BUILD_INTERFACE and INSTALL_INTERFACE.

From my searching around those get evaluated at non-configure time, so when the layers tries to do the FILE command later to determine the headers version we end up with a VulkanHeader_INCLUDE_DIRS with something like:

"/Users/dsinclair/Development/vulkan-validationlayers/$<BUILD_INTERFACE:/Users/dsinclair/Development/vulkan-validationlayers/external/Vulkan-Headers/include>;$<INSTALL_INTERFACE:include>/vulkan/vulkan_core.h"
which doesn't work so well

I'm currently seeing this in the ValidationLayers and in github.com/google/amber and github.com/google/vkb.

**Comment by mikew-lunarg** [comment]
@dj2 What version of CMake are you runnng?  FWIW we did test the original PR #110 with CMake 3.10.2 and our usual workflow, but not your usemodel.

@rbsheth @NeroBurner Please review this issue asap.  Without a prompt fix, I'll need to revert the PR

**Comment by dj2** [comment]
You can see one of the failed builds at: https://source.cloud.google.com/results/invocations/2bf10c8f-87e9-49e1-9cd7-f29c31b51793/targets/graphics_shader_compiler%2Fvkb%2Flinux-clang-release%2Fpresubmit/log  the error is at the bottom.

The version of cmake in there is `++ echo Wed Apr 22 08:12:54 PDT 2020: cmake version 3.10.2 CMake suite maintained and supported by Kitware '(kitware.com/cmake).'`

**Comment by NeroBurner** [comment]
will have a look

**Comment by mikew-lunarg** [comment]
@dj2 PR #110 has been reverted to undo this breakage asap.

PR #112 contains fixes for #110, and will be evaluated independently.

**Comment by dj2** [comment]
My build was successful. This can now be closed.
