### ISSUE TITLE
Update repository for Vulkan 1.2.138/1.2.139

### ISSUE THREAD

**Issue by Friz64** [KhronosGroup/Vulkan-Headers#113]
This repository is currently on version 1.2.137 and has been out of date for ~11 days.

Is there any reason why it is not being updated?

**Comment by oddhack** [comment]
Yes, there was a change in the Vulkan-Hpp repository that was causing many warnings from the generated C++ header. When that happens we hold off updating the headers until the problem is fixed. I think it has been now and will get an update out tonight if so.

**Comment by oddhack** [comment]
Headers updated for 1.2.139.
