### ISSUE TITLE
Please bring back sdk-1.2.135 branch

### ISSUE THREAD

**Issue by priv-kweihmann** [KhronosGroup/Vulkan-Headers#134]
When using latest YOCTO release the following happens
```
09:38:09  ERROR: vulkan-headers-1.2.135.0-r0 do_fetch: Fetcher failure: Unable to find revision fb7f9c9bcd1d1544ea203a1f3d4253d0e90c5a90 in branch sdk-1.2.135 even from upstream
09:38:09  ERROR: vulkan-headers-1.2.135.0-r0 do_fetch: Fetcher failure for URL: 'git://github.com/KhronosGroup/Vulkan-Headers.git;branch=sdk-1.2.135'. Unable to fetch URL from any source.
```

somehow the branch has been removed (or superseded by sdk-1.2.141).
As YOCTO is very picky about branches (for very good reasons) please bring back the branch.
Also I like to point out that I consider it a bad practice to remove release branches and this is very prone to various downstream errors

**Comment by shannon-lunarg** [comment]
I'm not sure how the Vulkan-Headers sdk-1.2.135 branch was removed but it has been restored. We are looking into the best solution for preventing accidental(?) deletion in the future. Thank you for bringing this to our attention.
