### ISSUE TITLE
ICD function prototype mismatch using MSVC

### ISSUE THREAD

**Issue by jpark37** [KhronosGroup/Vulkan-Headers#148]
It looks like these prototypes were recently added to vk_icd.h

VKAPI_ATTR VkResult VKAPI_CALL vk_icdNegotiateLoaderICDInterfaceVersion(uint32_t* pVersion);
VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL vk_icdGetInstanceProcAddr(VkInstance instance, const char* pName);
VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL vk_icdGetPhysicalDeviceProcAddr(VkInstance isntance, const char* pName);

I use __declspec(dllexport) in my code, so I get error C2375 about redefining with different linkage. I'm currently using VK_NO_PROTOTYPES to work around this, but maybe there's a better solution.

**Comment by charles-lunarg** [comment]
While exporting functions with `__declspec(dllexport)` necessarily changes the function definition (causing the MSVC warning), the alternative way to export the functions is with a Resource File (.rc) file. I am under the impression that using .rc files will bypass this MSVC warning and most ICD's use this. The vulkan loader uses an rc file as well. So the better solution is probably adding a .rc file.

I believe this change was to make `vk_icd.h` consistent with `vulkan.h` by providing function definitions and guarding it with VK_NO_PROTOTYPES. This let ICD's include the header in their implementation and have the compiler check the definition. (which is exactly whats happening to you, but MSVC gets antsy about the dllexport.)

I do not think `dllexport` will be added to the function definitions anytime soon, as the current definition is consistent with vulkan.h. It certainly is more convenient

**Comment by jpark37** [comment]
I think you mean a def file (vulkan-1.def) right? A resource file stores embedded icons and stuff like that. Seems like a reasonable alternative. Thanks.

**Comment by charles-lunarg** [comment]
Oh yes, my bad. Same principle, completely wrong name. 
If that's an adequate solution, the issue should probably be closed.
