### ISSUE TITLE
Request to move registry/vk.xml to registry/xml/vk.xml

### ISSUE THREAD

**Issue by timo-suoranta-varjo** [KhronosGroup/Vulkan-Headers#156]
In `Vulkan-Hpp/CMakeLists.txt`, path to `vk.xml` in  has some inconsistency.
`VulkanRegistry_DIR` cannot point to Vulkan-Docs, because inside it `vk.xml` is inside `xml` directory.
Meanwhile, Vulkan-Hpp `CMakeLists.txt` expects `vk.xml` to be found from directory called `registry`.

One possible solution is to move `Vulkan-Headers/registry/vk.xml` to `Vulkan-Headers/registry/xml/vk.xml`.

IMHO it is not ideal that Vulkan-Headers keeps copy of registry from Vulkan-Docs. It could be better to simply use files from Vulkan-Docs directly.

Cross-posted with https://github.com/KhronosGroup/Vulkan-Hpp/issues/793

**Comment by juan-lunarg** [comment]
Looks like this has already been addressed by Vulkan-Hpp:
https://github.com/KhronosGroup/Vulkan-Hpp/pull/796
