### ISSUE TITLE
WSI platform support needed for GGP (Stadia)

### ISSUE THREAD

**Issue by jdrouan-goog** [KhronosGroup/Vulkan-Headers#162]
Google Games Platform (GGP) is the platform for Stadia.

WSI support needs to be added to Vulkan-Headers/vk_icd.h, and to Vulkan-Loader.

Adding @lenny-lunarg for non-API headers

**Comment by jdrouan-goog** [comment]
Vulkan-Headers pull request: https://github.com/KhronosGroup/Vulkan-Headers/pull/163

Vulkan-Loader pull request: https://github.com/KhronosGroup/Vulkan-Loader/pull/519

**Comment by sunsun02** [comment]
Can the VK_ICD_WSI_PLATFORM_GGP be added to the end of VkIcdSurfaceIOS?

We had such issue before and fixed in
https://github.com/KhronosGroup/Vulkan-Headers/commit/a0f1f5149d91d9ea460c19a7bbd281a1c604c8e7#diff-d805e875e5a2732052348ff7c70cf2510b8f8890fc4a6a8471ba9c94448c9377

**Comment by lenny-lunarg** [comment]
@sunsun02 I'm an idiot. I should have realized that'll cause trouble. No loader built yet has actually incorporated that, so I'll just open a PR to fix it now.

**Comment by lenny-lunarg** [comment]
I just opened a PR to fix that (linked above). I'll give it a day or two too make sure no one points out any flaws in that and then I'll merge assuming no one has objected.

**Comment by sunsun02** [comment]
Excellent, thanks for the fix

**Comment by lenny-lunarg** [comment]
I'm closing this as the associated headers and loader changes have now been merged. This means that the minimum needed to run this should all be in. It doesn't include things like validation. If validation layer support is desired I'd recommend opening an issue on that repo.

**Comment by sunsun02** [comment]
Thanks
