### ISSUE TITLE
Unspecified extension VK_QNX_screen_surface

### ISSUE THREAD

**Issue by jcant0n** [KhronosGroup/Vulkan-Headers#182]
I use this xml to auto generate C# binding (https://github.com/WaveEngine/Vulkan.NET) and in the latest version there is an undefined extension VK_QNX_screen_surface.

Here is the extension, but if you search for vkCreateScreenSurfaceQNX or vkGetPhysicalDeviceScreenPresentationSupportQNX, these are not defined in the xml.

`<extension name="VK_QNX_screen_surface" number="379" type="instance" requires="VK_KHR_surface" platform="screen" author="QNX" contact="Mike Gorchak @mgorchak-blackberry" supported="disabled">
            <require>
                <enum value="1"                                         name="VK_QNX_SCREEN_SURFACE_SPEC_VERSION"/>
                <enum value="&quot;VK_QNX_screen_surface&quot;"         name="VK_QNX_SCREEN_SURFACE_EXTENSION_NAME"/>
                <enum offset="0" extends="VkStructureType"              name="VK_STRUCTURE_TYPE_SCREEN_SURFACE_CREATE_INFO_QNX"/>
                <type name="VkScreenSurfaceCreateFlagsQNX"/>
                <type name="VkScreenSurfaceCreateInfoQNX"/>
                <command name="vkCreateScreenSurfaceQNX"/>
                <command name="vkGetPhysicalDeviceScreenPresentationSupportQNX"/>
            </require>
        </extension>`

**Comment by dgkoch** [comment]
It's flagged as `supported="disabled"` so I'd think you should be ignoring it in your parser.

**Comment by osor-io** [comment]
Yeah, it caused a headache when doing https://github.com/osor-io/Vulkan to do bindings for Jai. Doesn't sound like a good practice to have vkCreateScreenSurfaceQNX and vkGetPhysicalDeviceScreenPresentationSupportQNX in referenced in there if they don't exist anywhere else in the document 😢

**Comment by mgorchak-blackberry** [comment]
Sorry for inconvenience, it should be fixed now.

**Comment by KarenGhavam-lunarG** [comment]
From the comments in this issue, I believe issue is closed. Re-open if you see it differently.

**Comment by theFJ1991** [comment]
- [ ]
