### ISSUE TITLE
Vulkan video headers are missing

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Headers#194]
Build with `VK_ENABLE_BETA_EXTENSIONS` fails:

```
include/vulkan/vulkan_beta.h:434:10: fatal error: 'vk_video/vulkan_video_codec_h264std.h' file not found
```

Are the video headers expected to land soon? I could attempt to remove `VK_ENABLE_BETA_EXTENSIONS` from VVL's `BUILD.gn`, but would rather not if this is something that'll be fixed soonish.

**Comment by oddhack** [comment]
Sorry about that. Please try now. I run a test during the build to ensure the headers all compile but the test didn't get updated for the new static headers so obviously it's not a good enough test, yet.

**Comment by ShabbyX** [comment]
Everything's fine on our end now!
