### ISSUE TITLE
VK_NULL_HANDLE issues with Visual Studio 2019

### ISSUE THREAD

**Issue by amerkoleci** [KhronosGroup/Vulkan-Headers#197]
After updating to latest headers I have issue with VK_NULL_HANDLE defined to ((void*)0).

Seams there is an issue with __cplusplus not working correctly and probably should be used _MSVC_LANG similar as vulkan.hpp.

Thanks

**Comment by oddhack** [comment]
Thanks. This duplicates https://github.com/KhronosGroup/Vulkan-Docs/issues/1502, so please track that. We'll fix ASAP.

**Comment by oddhack** [comment]
@amerkoleci could you test the fix attached to https://github.com/KhronosGroup/Vulkan-Docs/issues/1502#issuecomment-820831500 and report back in that issue? (I'd tag you over there instead since this is closed, but github won't let me).

**Comment by amerkoleci** [comment]
Can confirm, it works for me!

Thanks
