### ISSUE TITLE
Vulkan-Hpp planning to split vulkan.hpp into multiple files

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Headers#204]
Per https://github.com/KhronosGroup/Vulkan-Hpp/pull/979, Vulkan-Hpp is proposing to split vulkan.hpp into several different files. In terms of how it would impact *this* repository, I'd just change the process for updating the repo to include all those new files. But there are downstream impacts as other repositories consuming this one will need to copy / install all of the new files, not just vulkan.hpp. This is a tracker for getting feedback, particularly from downstream Khronos projects like the https://github.com/KhronosGroup/Vulkan-Loader .

Assigning to @KarenGhavam-lunarG as this is probably largely in LunarG's ballpark in terms of constructing SDKs and whatever internal use of vulkan.hpp your projects have.

**Comment by lunarpapillo** [comment]
Examining the **KhronosGroup/Vulkan-Hpp** change, I see that there's a second header already generated there that is not incorporated into this repository, `vulkan_raii.hpp`.  Should this header also be included, both here and by extension in the Vulkan SDK?

**Comment by jeremy-lunarg** [comment]
`vulkan_raii.hpp` is relatively new. I think it calls into `vulkan.hpp` and is completely optional. As to whether it should be included in Vulkan-Headers, I believe you should ask @asuessenbach.

**Comment by KarenGhavam-lunarG** [comment]
> This is a tracker for getting feedback, particularly from downstream Khronos projects like the https://github.com/KhronosGroup/Vulkan-Loader .

The loader is not impacted by this change. The Vulkan SDK packaging might have been impacted but we have verified that as long as all the HPP files are put into this repository, the SDK packaging will automatically pick them up.
