### ISSUE TITLE
'module' is a reserved keyword in c++20

### ISSUE THREAD

**Issue by HildarTheDorf** [KhronosGroup/Vulkan-Headers#211]
`module` is used as an identifier in vulkan.h, namely in VkPipelineShaderStageCreateInfo.

This is a keyword in C++ 20 and should be changed.

**Comment by charles-lunarg** [comment]
It is not a keyword. It is a  "identifier with special meaning".

Thus it only acts as a keyword in specific contexts, like at the beginning of a file. The C++ committee isn't daft and is well aware that the word module is used in many codebases, thus made sure to not trample on a vast majority of those uses, like type or variable names.

This exact issue has been adressed before in the vulkan-hpp repo, thus I am going to close this isseu.
https://github.com/KhronosGroup/Vulkan-Hpp/issues/121

**Comment by HildarTheDorf** [comment]
Just to add more information if anyone digs this issue up in future, this seems to only be an issue in clang 11. Clang 12 correctly treats `module` as an "identifier with special meaning" and it no longer causes a problem.
