### ISSUE TITLE
linker errors caused by vk::Instance::createDebugUtilsMessengerEXTUnique and vk::Instance::createDebugUtilsMessengerEXT

### ISSUE THREAD

**Issue by tzlils** [KhronosGroup/Vulkan-Headers#216]
```
/usr/bin/ld: CMakeFiles/engine.dir/src/main.cpp.o: in function `main':
main.cpp:(.text.startup+0x25a): undefined reference to `vkCreateDebugUtilsMessengerEXT'
/usr/bin/ld: main.cpp:(.text.startup+0x276): undefined reference to `vkDestroyDebugUtilsMessengerEXT'
collect2: error: ld returned 1 exit status
```
to reproduce: call instance->createDebugUtilsMessengerEXTUnique with valid arguments

**Comment by oddhack** [comment]
This repository isn't for bug reports, it's just a hosting mechanism for its contents. It isn't clear from the comment, but it appears that you are having a build issue with vulkan.hpp. If so, the most likely place to get assistance is the KhronosGroup/Vulkan-Headers repository, so please move the issue there.
