### ISSUE TITLE
KHR function in NV codeblock

### ISSUE THREAD

**Issue by Luke-Filewalker** [KhronosGroup/Vulkan-Headers#220]
PFN_vkGetRayTracingShaderGroupHandlesKHR in vulkan_core.h line 10264 is within the NV vendor function block. This could be a bit confusing.

**Comment by oddhack** [comment]
That's not something we directly control as the headers are generated from vk.xml, and is a consequence of some of the extension APIs being aliases of equivalent core APIs. There are other ways in which some of the APIs for an extension can pop up in different parts of the header. Sorry if it's confusing, but we're not going to spend time on this - at best a fairly intrusive scripting change would be required and it still couldn't address all such cases.

**Comment by Luke-Filewalker** [comment]
sorry thought this was a bug
