### ISSUE TITLE
Upcoming renaming of master -> main branch (update: will occur 2021-08-31)

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Headers#222]
@mark-lunarg @KarenGhavam-lunarG @asuessenbach @mtavenrath  and other interested parties: heads-up that we propose to rename the default branch of this repository to 'main' in late August 2021, following emerging Khronos & github practice (for Khronos members, see internal khronos-general issue 106). This should have very little impact, although if you have a checked-out repository clone, you may want to follow the simple instructions github will pop up on the repository webpage describing how to do the same locally.

If there is a concern about this, please raise it here by 2021-08-23.

Because this repository has many downstream consumers, I expect we'll need to do some internal review to make sure that this change won't be disruptive. Github's renaming tool covers many common use cases transparently (see https://github.com/github/renaming).

**Comment by oddhack** [comment]
@KarenGhavam-lunarG @mark-lunarg I haven't had any feedback on this and need to get affirmative signoff from LunarG before changing the default branch in this repository. Given the largely transparent rewriting that github will do, there should be minimal impact, but this repository is on a critical path for downstream work. Perhaps a logical time to set the new default branch would be when the Vulkan-Headers commit / tag corresponding to a new SDK is created?

**Comment by KarenGhavam-lunarG** [comment]
@oddhack If you could wait to make this change until after August 30 (and do it within the next two weeks), there won't be any issues.

**Comment by oddhack** [comment]
> @oddhack If you could wait to make this change until after August 30 (and do it within the next two weeks), there won't be any issues.

Do you mean, do it between August 31st - September 13th?

**Comment by KarenGhavam-lunarG** [comment]
> Do you mean, do it between August 31st - September 13th?

Yes

**Comment by oddhack** [comment]
> > Do you mean, do it between August 31st - September 13th?
> 
> Yes

OK. Scheduling for August 31st.

**Comment by oddhack** [comment]
I forgot to do this on August 31st, but it's still within the two week window @KarenGhavam-lunarG noted, so went ahead and changed the default branch to 'main' tonight. https://github.com/KhronosGroup/Vulkan-Headers/commit/569280430b427f27f72b1cb7d40ac7fb52fe2f6a updates the README accordingly. We aren't mirroring this through khronos.org AFAIK, so there's no action needed there.
