### ISSUE TITLE
Deploy tags when there are new releases

### ISSUE THREAD

**Issue by hcorion** [KhronosGroup/Vulkan-Headers#23]
Hi, I noticed that you detail the version number in the commit comments, but you haven't bothered to add a new tag, I'd like to request you add a new tag for every new release that gets covered in the commits.

**Comment by akien-mga** [comment]
Bump. No new tag since 1.1.92.0, which makes it difficult to distro packages to sync new versions.

**Comment by akien-mga** [comment]
Ah, if only some specific Headers versions are meant to be used with matching Loader/ValidationLayers tags, then it does make sense to tag only these. It does prevent careless distro maintainers like I may be to update Headers to the latest, only to find that there is no matching release in the rest of the SDK.

So this is probably good as is then, though maybe some information could be added to the README about the versioning scheme.

**Comment by oddhack** [comment]
It feels trivially cheap to tag each 'headers: update to 1.1.##' commit with tag 'v1.1.##' matching the Vulkan-Docs repo they come from, though I don't know the use case either.

**Comment by shannon-lunarg** [comment]
An update: Going forward, `Vulkan-Headers`, `Vulkan-Loader`, `Vulkan-ValidationLayers`, `Vulkan-Tools`, `LunarG-VulkanTools`, and `LunarG-VulkanSamples` will employ the `v`_`<version>`_ (e.g. - `v1.1.96`) tagging scheme when updating each repo in response to the latest Vulkan specification release.

It should be noted that occasionally one or more repositories do not require or receive an update in response to a new Vulkan spec release.

**Comment by akien-mga** [comment]
@shannon-lunarg Shouldn't version that correspond to a SDK release still be tagged additionally with `sdk-<version>`, as was done up to https://github.com/KhronosGroup/Vulkan-Headers/releases/tag/sdk-1.1.97.0?

I see SDK 1.1.101 was released, but https://github.com/KhronosGroup/Vulkan-Headers/releases/tag/v1.1.101 does not have an equivalent `sdk-1.1.101` tag.

I've seen that the SDK is now shipped with everything included on https://vulkan.lunarg.com/sdk/home, but for Linux distro packagers who still rely on packaging each component separately, those `sdk-<version>` tags were welcome :)

**Comment by shannon-lunarg** [comment]
@akien-mga You are absolutely correct! This was an oversight. I will have the sdk-1.1.101.0 tags out shortly.
