### ISSUE TITLE
v.1.2.192 tags points to .191 update commit

### ISSUE THREAD

**Issue by MarijnS95** [KhronosGroup/Vulkan-Headers#230]
@oddhack it looks like the [tag](https://github.com/KhronosGroup/Vulkan-Headers/tree/v1.2.192) created for https://github.com/KhronosGroup/Vulkan-Headers/pull/229 points to the 1.2.191 update at 4fee3efc189c83ccd26a9cd8265185c98458c94d, instead of the 1.2.192 update at c519fd7a3f3b3baf0df16395356cecf4bfee2a8c. Can you force-push this tag to point to the correct revision?

**Comment by oddhack** [comment]
Thanks. Should be fixed now.
