### ISSUE TITLE
Avoid windows.h

### ISSUE THREAD

**Issue by pc-john** [KhronosGroup/Vulkan-Headers#234]
I consider including windows.h evil and try to avoid it as much as possible. Including it may cause many troubles. And vulkan.h includes it if you specify VK_USE_PLATFORM_WIN32_KHR. The troubles fall into two categories:

1. Polluted namespace by thousands and thousands of symbols, including min, max, near, far and MemoryBarrier macros, making it difficult even to use stl library (e.g. std::max, or std::numeric_limits<uint64_t>::max(), .... - these clashes with above mentioned macros). Even vk_sdk_platform.h have to define NOMINMAX and #undef inline and vulkan.hpp have to #undef MemoryBarrier to fight the problems arising from all this. Using variables like near and far is not possible in your project without further #undefs. Other difficulties are probably waiting just behind the doors.
2. Compilation time is extended. The windows.h includes huge tree of other headers and I would not wonder if it would be the half of the whole WinAPI. Maybe not, but it is quite much. Thus, any vulkan project will compile much longer just because it defines VK_USE_PLATFORM_WIN32_KHR.

Would you be open to consider not including windows.h in vulkan headers? The vulkan.hpp is already doing that even although it calls some WinAPI functions. I was investigating and all that seems to be missing to avoid windows.h are the following typedefs:

```
typedef struct HINSTANCE__* HINSTANCE;
typedef struct HWND__* HWND;
typedef struct HMONITOR__* HMONITOR;
typedef void* HANDLE;
typedef /*_Null_terminated_*/ const wchar_t *LPCWSTR;
typedef unsigned long DWORD;
typedef struct _SECURITY_ATTRIBUTES SECURITY_ATTRIBUTES;
```

With these 7 lines, windows.h is no more needed, at least as far as I tested. And all the problems above disappear.

Edit: struct SECURITY_ATTRIBUTES changed to typedef struct _SECURITY_ATTRIBUTES SECURITY_ATTRIBUTES

**Comment by dgkoch** [comment]
The solution already exists - just don't include vulkan.h. 

See https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#_wsi_platform

> In order for an application to be compiled to use WSI with a given platform, it must either:
> - #define the appropriate preprocessor symbol prior to including the vulkan.h header file, or
> - include vulkan_core.h and any native platform headers, followed by the appropriate platform-specific header.

If you pick the second option you can include exactly what you want. 
vulkan.h is really just provided for compatibility at this point. vulkan_core.h is the preferred way.

**Comment by pc-john** [comment]
Thanks! Very good point! Unfortunately, I am using vulkan.hpp and I do not have such option. Vulkan.hpp always includes vulkan.h and expects the use of VK_USE_PLATFORM_WIN32_KHR to enable its Win32 functions and methods. So, I have to go the first way with the result of all the pains given by windows.h . That is the reason for my question whether there is a way to consider the replacement of it by definition of required symbols.

**Comment by oddhack** [comment]
The strongest argument is that vulkan.h is specified to include \<windows.h> in the Vulkan specification.

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/WSIheaders.html

**Comment by pc-john** [comment]
Thanks! Definitely, having that in the spec is very strong argument. I noticed it only yesterday when going through the spec. I understand that such change might be probably possible only in major releases, such as Vulkan 2.0, when backward compatibility is not necessarily kept in all directions.

This solution of vulkan_core.h and platform-specific headers is really great solution while keeping backward compatibility. I will go to vulkan.hpp people to see if they could make use of it.

Anyway, I see one more use case that might still not be handled properly/sufficiently even in this new approach. Let's forget about vulkan.hpp for the moment and let's imagine that a whole code base is using Vulkan dynamic loading through a large function pointer table. Only single file is calling WinAPI functions. So, the logical conclusion would be that all the sources would include vulkan_core.h while only single file will include vulkan_win32.h and windows.h . This would be very nice and effective solution. But the problem is in the Vulkan function pointer table that contains also declarations of Win32 Vulkan function pointers. Now the exact design: the whole code base include the header with this large function pointer table. The function pointer table includes vulkan_core.h, but it needs to include also vulkan_win32.h because of Win32 function prototypes. And because of vulkan_win32.h, it also needs to include windows.h and that is exactly what we do not want. Whole project would not include windows.h, while only single file is using Win32 API. So, we face the problem once again on different level.

As you advised, some "hacks" might be used that solve the problem. I could imagine that this function pointer table header would declare above mentioned seven symbols before including vulkan_win32.h and the problem is solved. Anyway, is it a clean solution? I am writing a Vulkan tutorial and teaching students how Vulkan API is nice and effective. Do I need to show them such a hack? If no way around, we have to live with that. Just asking. I understand very well that we definitely do not want to hit Vulkan developers with any problems. I am now considering how risky is to put the six typedefs and one forward declaration into vulkan_win32.h . These declarations does not interfere with windows.h anyway as long as the symbols are the same. I admit that tests outside MSVC might be needed (mingw,...). I can do that but only if it is reasonable.

**Comment by juan-lunarg** [comment]
FWIW `wayland-client.h` was recently removed from vulkan.h [here](https://github.com/KhronosGroup/Vulkan-Docs/pull/1905)

Seems like a similar situation to `windows.h`

**Comment by juan-lunarg** [comment]
Closing this issue

1.) `vulkan.h` doesn't belong to this repository.

It belong to https://github.com/KhronosGroup/Vulkan-Docs

The only header files this repo owns are:

- vk_icd.h
- vk_layer.h
- vk_sdk_platform.h

See the [README.md](https://github.com/KhronosGroup/Vulkan-Headers#vulkan-headers)

2.) Requires a spec change

That isn't the responsibility of this repository.

**Comment by pc-john** [comment]
Thanks Lunars anyway for all your efforts here. I will go through this issue and consider again what is relevant to post to https://github.com/KhronosGroup/Vulkan-Docs.
