### ISSUE TITLE
vulkan.hpp:  overwrites its own vkGetInstanceProcAddr with Null, causing crashes

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/Vulkan-Headers#239]
Upstream issue is https://github.com/KhronosGroup/Vulkan-Hpp/issues/1108

The vk::DispatchLoaderDynamic::init(vk::VkInstance) method uses vkGetInstanceProcAddr to overwrite vkGetInstanceProcAddr itself.

See https://github.com/KhronosGroup/Vulkan-Headers/blob/d594f70127b4198286b3472a48bee56e341259cd/include/vulkan/vulkan.hpp#L11864

But the value is NULL, because a valid 'instance' is provided and so it falls into the last row in the table in 4.1 "Command Function Pointers" https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#initialization-functionpointers

But then that causes a crash in the very next function pointer initialization call.

This bad behaviour was uncovered by a recent fix in the loader: KhronosGroup/Vulkan-Loader#692

**Comment by oddhack** [comment]
@dneto0 can this be closed now? We've had a couple of spec updates and the upstream fix presumably? has propagated here by now.

**Comment by oddhack** [comment]
Closing this on the assumption it was resolved from upstream.
