### ISSUE TITLE
Build error: unknown type name 'StdVideoEncodeH265SliceSegmentHeader'

### ISSUE THREAD

**Issue by rorgoroth** [KhronosGroup/Vulkan-Headers#259]
Hi, I'm building on MINGW toolchain and after the recent commit to vulkan-headers (https://github.com/KhronosGroup/Vulkan-Headers/commit/5c0fa1d68f48ab7fdb331d75f31efc11aa313090) I recieve an error building the loader:

```
/mingw64/x86_64-w64-mingw32/include/vulkan/vulkan_beta.h:731:11: error: unknown type name 'StdVideoEncodeH265SliceSegmentHeader'
  731 |     const StdVideoEncodeH265SliceSegmentHeader*    pSliceSegmentHeaderStd;
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /root/mingw/build/packages/vulkan-prefix/src/vulkan/loader/loader_common.h:32,
                 from /root/mingw/build/packages/vulkan-prefix/src/vulkan/loader/log.h:29,
                 from /root/mingw/build/packages/vulkan-prefix/src/vulkan/loader/log.c:29:
```
Full log: https://pastebin.com/nBQyG69Q

Thanks for your time.

**Comment by mikes-lunarg** [comment]
Duplicate of https://github.com/KhronosGroup/Vulkan-Docs/issues/1764

**Comment by oddhack** [comment]
@rorgoroth try current Vulkan-Headers and please report if it's fixed the problem or not.

**Comment by rorgoroth** [comment]
> @rorgoroth try current Vulkan-Headers and please report if it's fixed the problem or not.

Builds fine now, thanks :)
