### ISSUE TITLE
> @jcant0n I haven't found another place where I can ask this question so I'll try here.

### ISSUE THREAD

**Issue by theFJ1991** [KhronosGroup/Vulkan-Headers#265]
> @jcant0n I haven't found another place where I can ask this question so I'll try here.
> 
> Would the Evergine team consider releasing the low level graphics API as open source?
> 
> It seems to make use of Veldrid which is also open source but has evolved a lot and added other platforms.
> 
> This would be very useful standalone or even as a contribution back to Veldrid.

_Originally posted by @theFJ1991 in https://github.com/EvergineTeam/Vulkan.NET/issues/6#issuecomment-1037265045_

**Comment by oddhack** [comment]
This has nothing to do with this repository (or with any KhronosGroup repository). You'll need to ask whomever makes that software.
