### ISSUE TITLE
Missing validusage.json in v1.3.207 update?

### ISSUE THREAD

**Issue by mikes-lunarg** [KhronosGroup/Vulkan-Headers#269]
validusage.json still lists version 206:
```
  "version info": {
    "schema version": 2,
    "api version": "1.3.206",
    "comment": "from git branch: github-main commit: d80b6159f6d69398dbeae52aa1080e47ae96fe47",
    "date": "2022-02-17 16:04:58Z"
  },
```

It isn't urgent to fix, but Vulkan-ValidationLayers will report some extra spec consistency errors until it is updated.

**Comment by oddhack** [comment]
Sorry! Left out accidentally. I've put it in and re-set the v1.3.207 tag accordingly.
