### ISSUE TITLE
Older SDK branches appear to have disappeared

### ISSUE THREAD

**Issue by jukim-nv** [KhronosGroup/Vulkan-Headers#284]
Hello, we're seeing that the specific SDK branch that our repo was using (sdk-1.2.170) is no longer found.  Looking at the github page and `git show-ref` output, it looks like the branches that used to exist for older SDK versions are no longer there (although tags still exist).  `sdk-1.3.211` is the only remaining SDK branch.  Were these branches removed intentionally?  I found this previous closed issue which seems to describe something similar that happened in the past: https://github.com/KhronosGroup/Vulkan-Headers/issues/134.

We first saw this behavior appear on 2022-05-26.

**Comment by oddhack** [comment]
I screwed up trying to prune some dead branches. All the sdk-* and tmp-* branches that I could tell were affected have been pushed back from my local clone; please let me know if this looks OK.

**Comment by acmarrs-nvidia** [comment]
I am able to see the sdk-* branches, including the one we're using. A fresh clone of our project successfully pulls the sdk branch submodule. Looks fixed to me, thanks!
