### ISSUE TITLE
M

### ISSUE THREAD

**Issue by Deloww** [KhronosGroup/Vulkan-Headers#309]
**Is this issue appropriate for the repository?**

Vulkan-Headers exists as a publishing mechanism for headers and related material sourced from multiple other repositories. If you have a problem with that material, it should *not* be reported here, but in the appropriate repository:

- https://github.com/KhronosGroup/Vulkan-Docs - C headers, XML, validusage.json, and generation scripts
-  https://github.com/KhronosGroup/Vulkan-Hpp - C++ headers
- This repository - Repository structure, management, and build system *only*

See the repository README for more details.

**Describe the bug**

A clear and concise description of what the bug is. Please refer to specific files that are only in this repository, not copied from Vulkan-Docs or Vulkan-Hpp.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by oddhack** [comment]
Issue has no content.
