### ISSUE TITLE
vk_sdk_platform.h should be removed

### ISSUE THREAD

**Issue by jeremyg-lunarg** [KhronosGroup/Vulkan-Headers#316]
This file contains some very minor platform / compiler macro definitions that IMO don't belong in Vulkan-Headers at all. None of the macros in this file are used by any of the other headers in Vulkan-Headers.  Applications that need them would be better served by defining what they need in their own cross platform code.

However, this header is included by several repositories on github, including some not part of KhronosGroup.  There is likely other code not on github using this header.  Any effort to remove the header file would probably need to be staged carefully, and include a phase where the header is marked deprecated somehow so that people have time to fix stuff before it is removed completely.

**Comment by jeremyg-lunarg** [comment]
cc: @oddhack - your question in https://github.com/KhronosGroup/Vulkan-Docs/issues/1975 lead to me having even more questions about this header.

**Comment by jeremyg-lunarg** [comment]
@oddhack when you are updating Vulkan-Docs readmes, can you please recommend people to NOT use this header?

**Comment by oddhack** [comment]
Re "marking deprecated" it comes up many times that we'd like to communicate something like this to "the developer community" but have no great channel for doing so. TDC seems diffused across many websites and channels.

**Comment by jeremyg-lunarg** [comment]
> Do you mean the Vulkan-Docs spec repository README, or the one here? Either way, please propose a PR/MR. Maybe having the header self-document that it's deprecated would be more likely to be seen, though?

I was referring to your comment here https://github.com/KhronosGroup/Vulkan-Docs/issues/1975#issuecomment-1303627852 and I thought you were already working a PR to update docs.  But yes, having the header issue a warning or something is better and once we have an owner identified that should be part of the process for fixing this.

Also both [VVL ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4753 )and [Vulkan-Loader](https://github.com/KhronosGroup/Vulkan-Loader/pull/1057) were including this header for no reason.

**Comment by oddhack** [comment]
I already committed a change to the Vulkan-Headers README which removed a comment telling people to report issues on these files to Vulkan-Loader. If we establish an owner for these headers, we should note that in the issue template for Vulkan-Headers, at least.

**Comment by oddhack** [comment]
Popping a #warning in seems plausible - it is a C99 construct and Vulkan is a C99 API by definition so that should just work everywhere, right? \<crosses fingers>
