### ISSUE TITLE
Possible +x bit missing on /usr/share/vulkan/registry/*.py

### ISSUE THREAD

**Issue by jengelh** [KhronosGroup/Vulkan-Headers#336]
After `make install` of SDK-1.3.236.0, rpmlint has this to say about the resulting files:

```
[    9s] vulkan-headers.noarch: E: non-executable-script /usr/share/vulkan/registry/apiconventions.py 644 /usr/bin/python3 -i
[    9s] vulkan-headers.noarch: E: non-executable-script /usr/share/vulkan/registry/cgenerator.py 644 /usr/bin/python3 -i
[    9s] vulkan-headers.noarch: E: non-executable-script /usr/share/vulkan/registry/generator.py 644 /usr/bin/python3 -i
[    9s] vulkan-headers.noarch: E: non-executable-script /usr/share/vulkan/registry/genvk.py 644 /usr/bin/python3
[    9s] vulkan-headers.noarch: E: non-executable-script /usr/share/vulkan/registry/reg.py 644 /usr/bin/python3 -i
[    9s] vulkan-headers.noarch: E: non-executable-script /usr/share/vulkan/registry/spec_tools/conventions.py 644 /usr/bin/python3 -i
[    9s] vulkan-headers.noarch: E: non-executable-script /usr/share/vulkan/registry/vkconventions.py 644 /usr/bin/python3 -i
[    9s] This text file contains a shebang or is located in a path dedicated for
[    9s] executables, but lacks the executable bits and cannot thus be executed. If the
[    9s] file is meant to be an executable script, add the executable bits, otherwise
[    9s] remove the shebang or move the file elsewhere.
```

When there is a `#!` line, rpmlint tends to think these files should be 755. However, `#!` lines are also used to just trigger editors load certain syntax highlighting definitions, without any intent on behalf of the developer to have files runnable (e.g. lack of a "main" function or so). I would like to know which it is so we can fix the +x, or chose to ignore the warning in downstream distros.

**Comment by oddhack** [comment]
I don't know who is constructing the package you're installing, but in both the Vulkan-Docs repo and Vulkan-Headers, genvk.py has the exec bit set, so it sounds like something is being lost - I suggest reporting to to whomever provides vulkan-headers.noarch. The other scripts are all imported and would not even potentially be invoked directly. N.b. genvk.py can be invoked directly in arcane debugging circumstances, but normally is just called as 'python3 genvk.py' from makefiles and build scripts.

If that answers the question, please close. I don't think there's anything we can do in this repo.

**Comment by oddhack** [comment]
(I should perhaps add, genvk.py has the exec bit set in my clone of Vulkan-Headers - I can't quite tell from the github UI whether that's true in the upstream but I don't know why it wouldn't be.)

**Comment by MarijnS95** [comment]
```console
$ git ls-files -s registry/genvk.py
100755 4cd362f02e343694c465f62f354d6e4773851a1c 0	registry/genvk.py
```

`+x` is set for `ugo`.

**Comment by jengelh** [comment]
though genvk.py has the +x bit, cmake install does not transfer the bit over.

```
install(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/registry" DESTINATION ${CMAKE_INSTALL_DATADIR}/vulkan)
```

I'm not versed in cmake, but systems like automake for example make a distinction between "data" and "scripts" (one gets installed -x, but other +x), and perhaps cmake has something similar you need to use.

apiconventions.py is -x in git (but still has #! line). This is where the question was aimed. The #! looks to serve just as a syntax hint, so me (as the packager) added an ignore directive.

**Comment by juan-lunarg** [comment]
My PR partially address this issue.
https://github.com/KhronosGroup/Vulkan-Headers/pull/337

Note this only fixes the problem for `genvk.py`. The other python files will need to be updated to not have the shebang. Since it looks like they aren't meant to be standalone python scripts (they look more like python modules).

Those files would need to be updated in the Vulkan-Docs repository:
https://github.com/KhronosGroup/Vulkan-Docs

**Comment by juan-lunarg** [comment]
Closing this issue since there is nothing more that can be done in this repository now that CMake preserves the file permissions as of #337 

To fix the remaining `rpmlint` issues, that will need to addressed in https://github.com/KhronosGroup/Vulkan-Docs

**Comment by jengelh** [comment]
Nah, rpmlint is a more of a distro matter. Thanks everyone here and for #337.
