### ISSUE TITLE
Setting target_include_directories with generator expression breaks configuration of layers

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/Vulkan-Headers#351]
**Describe the bug**

`Vulkan-Headers` and `Vulkan-ValidationLayers` are included in my project as submodules via `add_subdirectory`.
During CMake configuration step of `Vulkan-ValidationLayers` I get an error at [line](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/4050be7c1960ae0aec00b421bb47be8d67cabe63/layers/CMakeLists.txt#L25) where `VulkanRegistry_DIR` get `$<BUILD_INTERFACE:/home/anatoliy/Projects/sah_kd_tree/external/Vulkan-Headers/registry>`. As you can see there is unevaluated generator expression, that comes directly from the [line](https://github.com/KhronosGroup/Vulkan-Headers/blob/24115c70bea4bb91e7bd12ef093fbdf6aa9a5222/CMakeLists.txt#L56). It is expected, because *generator expression* evaluated at step when *generator works*, not at *configuration step*. Therefore `EXISTS` failed.

**Expected behavior**
Project configured.

**Comment by juan-lunarg** [comment]
For clarification the validation layers consume Vulkan-Headers via `find_package`.

Which produces `VulkanHeadersConfig.cmake`

Which contains this line:
```
# Create imported target Vulkan::Registry
add_library(Vulkan::Registry INTERFACE IMPORTED)

set_target_properties(Vulkan::Registry PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/share/vulkan/registry"
)
```

I'm not sure how your build even got passed this line in VVL:
```
find_package(VulkanHeaders REQUIRED CONFIG QUIET)
```

FWIW package managers like Conan/vcpkg help avoid this scenario entirely.

**Comment by juan-lunarg** [comment]
It might be worth considering deprecating Vulkan::Registry entirely though due to this awkward difference between the `add_subdirectory` / `find_package` use scenario...

**Comment by tomilov** [comment]
`FWIW package managers like Conan/vcpkg help avoid this scenario entirely.`
I sure many users use Vulkan* libraries via git submodules + add_subdirectory.
