### ISSUE TITLE
Deleting old master branch?

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-Headers#366]
~~Is it okay to delete these 2 branches? AFAIK it is, but I'd like to be sure.~~

It it okay to delete master?

master
- https://github.com/KhronosGroup/Vulkan-Headers/tree/master

~~sc_main~~
~~https://github.com/KhronosGroup/Vulkan-Headers/tree/sc_main~~

CC @oddhack

**Comment by dgkoch** [comment]
Do NOT delete `sc_main`!

It is not stale. It's the primary source of the Vulkan SC headers.

**Comment by juan-lunarg** [comment]
> Do NOT delete `sc_main`!
> 
> It is not stale. It's the primary source of the Vulkan SC headers.

Gotcha, I've added a minimal branch protection rule to highlight it's current usage. (It just requires users sign the CLA)

**Comment by oddhack** [comment]
It's OK to delete master. It's been over a year since the default branch renaming.

**Comment by juan-lunarg** [comment]
master has been deleted
