### ISSUE TITLE
[registry] operator precedence in extension dependencies was left undefined

### ISSUE THREAD

**Issue by 1ace** [KhronosGroup/Vulkan-Headers#380]
The new dependencies syntax is documented here:
https://registry.khronos.org/vulkan/specs/1.3/registry.html#_attributes_of_extension_tags

There are 3 operators: `,` OR, `+` AND, and `()` grouping, however, the precedence of the two AND & OR operators is not defined.

Intuitively, I would expect `ext1+ext2,ext3` to be grouped as `(ext1+ext2),ext3`, but the only example in `vk.xml` that uses both AND & OR right now also uses the grouping parentheses in a way that implies that the *opposite* precedence would apply without them:
```xml
<extension name="VK_KHR_buffer_device_address" depends="(VK_KHR_get_physical_device_properties2+VK_KHR_device_group),VK_VERSION_1_1">
```

That seems counter-intuitive, so I think it's worth being explicit in the spec, whichever way was intended.

/cc @gfxstrand

**Comment by juan-lunarg** [comment]
See the contributing.md (https://github.com/KhronosGroup/Vulkan-Headers/blob/main/CONTRIBUTING.md)

Post this issue to the specification repository (https://github.com/KhronosGroup/Vulkan-Docs)

**Comment by 1ace** [comment]
Ah, thanks @juan-lunarg for directing me to the correct repo :)

Issue copied there: https://github.com/KhronosGroup/Vulkan-Docs/issues/2062
