### ISSUE TITLE
Spelling error in code

### ISSUE THREAD

**Issue by AurelioSilver** [KhronosGroup/Vulkan-Headers#387]
https://github.com/KhronosGroup/Vulkan-Headers/blob/fa204df59c6caea6b9be3cf0754a88cd89056a87/include/vulkan/vk_icd.h#L81

isntance -> instance

Not sure if this is the right place to report this.

**Comment by juan-lunarg** [comment]
`vk_icd.h` belongs to this repo. This is the right place.

**Comment by juan-lunarg** [comment]
Thanks for pointing out this issue @AurelioSilver :+1:
