### ISSUE TITLE
`#define`ing enum values breaks validation layer build

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-Headers#40]
I noticed a build issue when rolling vulkan repos within ANGLE forward. In `vulkan_core.h`, I see the following:

```
typedef enum VkFilter {
    VK_FILTER_NEAREST = 0,
    VK_FILTER_LINEAR = 1,
    VK_FILTER_CUBIC_EXT = 1000015000,
    VK_FILTER_BEGIN_RANGE = VK_FILTER_NEAREST,
    VK_FILTER_END_RANGE = VK_FILTER_LINEAR,
    VK_FILTER_RANGE_SIZE = (VK_FILTER_LINEAR - VK_FILTER_NEAREST + 1),
    VK_FILTER_MAX_ENUM = 0x7FFFFFFF
} VkFilter;

...

#define VK_FILTER_CUBIC_EXT               1000015000
```

In `parameter_validation.cpp` generated by the validation layers, there is a line that reads:

```
const std::vector<VkFilter> AllVkFilterEnums = {VK_FILTER_NEAREST, VK_FILTER_LINEAR, VK_FILTER_CUBIC_EXT, };
```

This causes a build error, where the mixture `{VkFilter, VkFilter, int}` is causing the compiler to not be able to match the appropriate constructor of the vector. I can verify this is really the issue by casting the third parameter to `VkFilter` which resolves the compile error:

```
const std::vector<VkFilter> AllVkFilterEnums = {VK_FILTER_NEAREST, VK_FILTER_LINEAR, (VkFilter)VK_FILTER_CUBIC_EXT, };
```

The issue is that `vulkan_core.h` is defining `VK_FILTER_CUBIC_EXT` twice, once correctly in the `VkFilter` enum and another time as an `int`-typed number through a define.

---

My suggestions are to either not `#define` the constants that are already added to the enums, or if necessary (for example to later test `#ifdef VK_FILTER_CUBIC_EXT`), define them cast properly to the type:

```
#define VK_FILTER_CUBIC_EXT               ((VkFilter)1000015000)
```

**Comment by ShabbyX** [comment]
Note how the old `VK_FILTER_CUBIC_IMG` was never `#define`d to a value (but now is `#define`d to `VK_FILTER_CUBIC_EXT` which is fine).

My point being that the script that's generating the header used to be doing the right thing. I haven't noticed any other ext doing this, so this seems to be an edge case.

**Comment by karl-lunarg** [comment]
This repo is mostly a downstream repo of Vulkan-Docs.

It looks like the problem has been found and fixed here:   https://github.com/KhronosGroup/Vulkan-Docs/pull/912.

At this point, I don't know if they will take  https://github.com/KhronosGroup/Vulkan-Docs/pull/912 in time for the next publication of the spec.

**Comment by ShabbyX** [comment]
Thanks, it's enough for me to know it's already addressed.

**Comment by oddhack** [comment]
It was addressed in a different internal MR, but the problem should? be gone now. To be clear about the source of the problem, there's nothing wrong with the generation scripts; they are simply doing what the XML told them to do. The problem was that the MR introducing this change edited the XML to try and express the aliasing, but didn't specify that the aliases were also part of the enumerated type. That's a pretty subtle thing to catch by visual inspection.
