### ISSUE TITLE
1.3.252 generator imports modules existing only in VulkanSC-Headers

### ISSUE THREAD

**Issue by incertia** [KhronosGroup/Vulkan-Headers#407]
[This](https://github.com/KhronosGroup/Vulkan-Headers/commit/605dc6d3e789630d24310435121cd0c7d51b6483#diff-6ab106ae5598d3b653cc5a1b638daf58e40a9ca623c971410e19c65e2edcfd35R19-R24) update imports non-existent python modules into the generator, but the modules exist in [VulkanSC-Headers](https://github.com/KhronosGroup/VulkanSC-Headers/tree/sc_main/registry)

**Comment by oddhack** [comment]
Which modules?

**Comment by incertia** [comment]
It appears as if `registry/genvk.py` will attempt to import from

* `json_parser`
* `schema_generator`
* `json_generator`
* `json_h_generator`
* `json_c_generator`
* `docgenerator`
* `extensionmetadocgenerator`
* `interfacedocgenerator`
* `spirvcapgenerator`
* `hostsyncgenerator`
* `formatsgenerator`
* `syncgenerator`
* `jsgenerator`
* `pygenerator`
* `rubygenerator`
* `reflib`
* `validitygenerator`

but they do not exist in the Vulkan-Headers registry

**Comment by oddhack** [comment]
TBH I'm not sure why genvk.py is here, other than that some downstream repos use a similar script to build their targets using their own generators and want to be able to keep in sync with changes in genvk.py.  It would take a very long time to check with every downstream consumer and find out if or how they're using this file, so I don't want to remove it. But there's no intention that people actually run the script in this repository for any of the targets it supports - you should be using Vulkan-Docs for that. I can add a note to that effect in the README if that would help.

**Comment by incertia** [comment]
It would probably make sense to add a note in the README. This issue mostly arised because I saw `genvk.py` within archlinux's `vulkan-headers` package (based on this repository) but it didn't seem to work. The Vulkan-Docs based package only installs the HTML docs but that is a packaging issue.

**Comment by oddhack** [comment]
I should also clarify what the repository is actually for. There's a bunch of stuff in here which is a snapshot of generated files from published spec updates. The actual C/C++ header files are probably all that should be packaged by a downstream distro. The other stuff is not provided for developers using Vulkan in their apps, but for people doing downstream ecosystem components like CTS, validation layers, language bindings, and so on. That isn't made clear today.

**Comment by oddhack** [comment]
@incertia please check if #408 helps clarify the repository contents / purpose.
