### ISSUE TITLE
Vulkan-Hpp now includes `.cppm` C++20 module; inclusion in Vulkan-Headers

### ISSUE THREAD

**Issue by sharadhr** [KhronosGroup/Vulkan-Headers#410]
As of earlier today, effort to develop a C++20 module interface file has been completed and merged into Vulkan-Hpp, called [`vulkan.cppm`](https://github.com/KhronosGroup/Vulkan-Hpp/blob/main/vulkan/vulkan.cppm). 

Is there a chance this file could be added to `Vulkan-Headers` and thence downstream, too? 

Thanks!

**Comment by juan-lunarg** [comment]
> Is there a chance this file could be added to Vulkan-Headers and thence downstream, too?

@oddhack handles updating the files from Vulkan-Hpp so I will defer to them. I don't see an issue with mirroring this file.

If we do mirror the file we should update the docs in this repo to state that we mirror the file explicitly. Currently our documentation lists that we only mirror *.hpp files from Vulkan-Hpp:

```
Vulkan C++ Binding Repository (https://github.com/KhronosGroup/Vulkan-Hpp)

As of the Vulkan-Docs 1.2.182 spec update, the Vulkan-Hpp headers have been split into multiple files. All of those files are now included in this repository.

    include/vulkan/*.hpp
```

**Comment by juan-lunarg** [comment]
> Sounds good. Should I start a PR for this?

I believe there is a process for getting files mirrored in from the Vulkan-Docs and Vulkan-Hpp.

I'll have to defer to @oddhack since it would impact their workflow.

**Comment by oddhack** [comment]
The .cppm file is published in Vulkan-Headers as part of the spec update process now. I tweaked CONTRIBUTING.md to note the new file but suggest @sharadhr review the README etc. to see if anything else needs to be added; if not this can be closed.

**Comment by sharadhr** [comment]
Looks good to me; no changes needed. Thanks for the quick updates!
