### ISSUE TITLE
v1.3.257 tag not pointing at main branch

### ISSUE THREAD

**Issue by mikes-lunarg** [KhronosGroup/Vulkan-Headers#421]
It looks like the `v1.3.257` tag is pointing at a commit one-past where it usually points, and that commit is not on the main branch. Was this intentional or can we get it moved back to `485c039 Update for Vulkan-Docs 1.3.257`?

**Comment by oddhack** [comment]
No idea what happened, but it should be fixed now. I will pay closer attention next update to see what might have caused that. Probably something got out of sync between my local repo clone and the upstream before I assigned the tag, but the contents of my working branch and main are identical so it was a spurious (empty) merge commit or like that.
