### ISSUE TITLE
Create a Security Policy

### ISSUE THREAD

**Issue by joycebrum** [KhronosGroup/Vulkan-Headers#430]
[Not a bug]
Hi, I'd like to suggest a security policy to Vulkan-Headers similar to the ones suggested to [glslang](https://github.com/KhronosGroup/glslang/issues/3168), [opengl-registry](https://github.com/KhronosGroup/OpenGL-Registry/issues/567) and [spirv-headers](https://github.com/KhronosGroup/SPIRV-Headers/issues/352).

A Security Policy is a GitHub standard document that provides instructions on how to report vulnerabilities in a safe and efficient way. It can be found in the "Security Tab" or in the main page of a repository.

![image](https://github.com/KhronosGroup/SPIRV-Tools/assets/22223372/4a812ab9-19cc-431a-9b18-327053c564a3)

The Security Policy is a [Scorecard Recommendation](https://github.com/ossf/scorecard/blob/main/docs/checks.md#security-policy) and a [GitHub Recommendation](https://docs.github.com/en/code-security/getting-started/securing-your-repository#setting-a-security-policy), meaning that it is considered a best practice for improving the security of a project.

I will be submitting a suggestion of Security Policy, the same used for other KhronosGroup repos. Please feel free to edit it directly or ask me for revisions until it is in compliance with how Vulkan-Headers would best handle vulnerability reports.

**Comment by juan-lunarg** [comment]
Sorry I was on vacation. I'll start taking a look.

**Comment by juan-lunarg** [comment]
Thanks @joycebrum I've added the security policy. I would have merged your PR but it appears to have been opened in your fork. Not on this repo.

Regardless it looks good now.

**Comment by joycebrum** [comment]
Ah my bad, I didn't noticed it. But thanks for migrating it to the right repo!
