### ISSUE TITLE
Missing new hpp file vulkan_hpp_macros.hpp

### ISSUE THREAD

**Issue by mikes-lunarg** [KhronosGroup/Vulkan-Headers#437]
There is a new Vulkan-Hpp file added in https://github.com/KhronosGroup/Vulkan-Hpp/commit/d4704cce01ba5e27caa25ddd37e8fbb251d30032 that needs to be published here, vulkan_hpp_macros.hpp.

Currently causing build failures at `#include <vulkan/vulkan.hpp>`

```cpp
In file included from cube/cube.cpp:43:
Vulkan-Headers/build/install/include/vulkan/vulkan.hpp:15:10: fatal error: vulkan/vulkan_hpp_macros.hpp: No such file or directory
   15 | #include <vulkan/vulkan_hpp_macros.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by oddhack** [comment]
Should be fixed now. I updated the v1.3.264 tag to point to new HEAD after the file was added.
