### ISSUE TITLE
People are trying to run genvk.py out of this repository

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Headers#449]
This does not work, nor is expected to (see the README), since most of the dependent script imports are not copied from Vulkan-Docs. But I'm not entirely sure why we are putting genvk.py here in the first place - as it stands, it is only useful to compare to previous tags and see if generator options changed. Can someone involved with the SDK speak to how you're using this script? Not sure how to direct the question, so tagging in a couple of recent VVL contributors.

The path of least resistance would be to include basically the entire contents of Vulkan-Docs/scripts here, but then there is an expectation of documentation / support for all that in this repo which I'd prefer not to take on.

**Comment by spencer-lunarg** [comment]
Speaking for Validation Layers (and probably any other tool in the SDK but @mikes-lunarg  can confirm) we don't not use `genvk.py` at all and would be ok if this file was not added to headers

**Comment by Tony-LunarG** [comment]
I see no reason it's needed here

**Comment by mikes-lunarg** [comment]
Historically we have only used genvk.py as a reference for updating the forked copies of that script that live in the various repos (lvl_genvk.py, loader_genvk.py, kvt_genvk.py). We could just as easily reference the copy in Vulkan-Docs for that purpose.

**Comment by oddhack** [comment]
> Historically we have only used genvk.py as a reference for updating the forked copies of that script that live in the various repos (lvl_genvk.py, loader_genvk.py, kvt_genvk.py). We could just as easily reference the copy in Vulkan-Docs for that purpose.

The INTEGRATION.md in Vulkan-Headers explicitly calls out updating those by reference to genvk.py - presumably that should be altered when we take genvk.py out?

**Comment by oddhack** [comment]
I made #451 to remove genvk.py. However, it raises the question of whether *any* of the Python scripts are actually needed in Vulkan-Headers?

**Comment by spencer-lunarg** [comment]
we use `reg.py`, `parse_dependency.py`, `generator.py`, `vkconventions.py` for sure I know
