### ISSUE TITLE
Assessment of the difficulty in porting CPU architecture for vulkan-headers

### ISSUE THREAD

**Issue by wangyuliu** [KhronosGroup/Vulkan-Headers#456]
Hello everyone! I am working on implementing a tool to assess the complexity of CPU architecture porting. It primarily focuses on RISC-V architecture porting. In fact, the tool may have an average estimate of various architecture porting efforts.My focus is on the overall workload and difficulty of transplantation in the past and future,even if a project has already been ported.As part of my dataset, I have collected the **vulkan-headers** project. **I would like to gather community opinions to support my assessment. I appreciate your help and response!** Based on scanning tools, the porting complexity is determined to be  simple, with a small amount of code related to the CPU architecture in the project.  Is this assessment accurate?Do you have any opinions on personnel allocation and consumption time？ I look forward to your help and response.

**Comment by juan-lunarg** [comment]
AFAIK `Vulkan-Headers` should just work on `RISC-V`. There is very little code related to the CPU architecture in this project.

Perhaps @oddhack would know more if anyone has already done `RISC-V` work.

**Comment by juan-lunarg** [comment]
Just checked Ubuntu has packages for `RISC-V` already available for use:
https://packages.ubuntu.com/search?suite=jammy&arch=riscv64&searchon=names&keywords=vulkan

So it seems like you are ready to go as far as I can tell.

**Comment by juan-lunarg** [comment]
Closing since there isn't a specific issue and Vulkan appears to compile fine for `RISC-V` furthermore. You seem to just have copy pasted this same issue into 20+ repositories.

If you have a specific issue with `RISC-V` that pertains to this repository open a new issue with the problem you are having.
