### ISSUE TITLE
How to manage expected Vulkan-Hpp breakage this week?

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Headers#46]
@shannon-lunarg @mark-lunarg @nsubtil @mtavenrath I think it's nearly certain there will be breakage of Vulkan-Hpp when I try to build the update to this repo for the next Vulkan-Docs update. There are at least two, and maybe three MRs going into that which break hpp-generate in CI.

How do you want to handle this? My expectation is that I'll update a branch of this repo as best I can and then create an MR, but not merge it until the build issues are resolved. Unfortunately Vulkan-Docs has a variety of downstream dependencies now that can and do get broken on a fairly regular basis, and fixing them is outside the direct control of the Vulkan Working Group. The specific thing that will be annoying in this case is that there are a variety of new extensions going into this update, and until we can update Vulkan-Headers with at least the C headers, nobody will be able to use those extensions.

**Comment by KarenGhavam-lunarG** [comment]
@oddhack Your assumption that you would create an MR and not merge until the build issues is resolved is a good assumption! Thanks

**Comment by oddhack** [comment]
Closing, 1.1.105 update is working and has been merged.
