### ISSUE TITLE
Add new AV1 video headers to BUILD.gn

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Headers#469]
@juan-lunarg as @soltiGG pointed out in https://github.com/KhronosGroup/Vulkan-Headers/commit/5a5c9a643484d888873e32c5d7d484fae8e71d3d#commitcomment-138334031 that the new AV1 extension added some new video headers which should be in BUILD.gn. Since that's not part of the repo I handle, can you take this? N.b. I can't seem to assign this issue to you for some reason, maybe the team membership is messed up?

Perhaps the BUILD.gn script could wildcard headers in the include directories? We can add new headers at any point, so the script should try to accommodate that without adding another thing to be manually updated. From my perspective, I just copy everything that comes out of Vulkan-Docs and Vulkan-Hpp header generation into the MR here.

**Comment by oddhack** [comment]
@juan-lunarg I sent an invite to the repository team - for some reason you are not on the Vulkan team so I'll send an invite there as well. You can also have Admin access if you want it, since you're responsible for a lot of stuff here.

**Comment by charles-lunarg** [comment]
> Perhaps the BUILD.gn script could wildcard headers in the include directories?
I do not believe build.gn supports wildcards, so I do not think that is a workable solution. I could be wrong, but having to list out the header files in addition to the source files would indicate to me that gn wants to be explicit about the inputs.
