### ISSUE TITLE
Vulkan-Module causing widespread problems in ecosystem

### ISSUE THREAD

**Issue by charles-lunarg** [KhronosGroup/Vulkan-Headers#506]
The recent addition of the Vulkan-Module created a lot of problems for downstream consumers of the Vulkan-Headers. 

I propose to disable Vulkan-Module by default, allowing projects to enable it if they so choose. The fact that I developed extensive logic to disable the modules indicates that the support for modules is still not as solid as it should be to enable by default. 

The most recent example is the Vulkan-ValidationLayers breaking builds on Fedora due to using symlinks to clang. https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8732

@sharadhr What are your thoughts, since you have extensive module experience.

**Comment by sharadhr** [comment]
Happy to set the default to 'off', and allow users to switch it on as they see fit. That being said, you might want to keep that logic to enable modules around—it might be useful. Although frankly CMake should provide such a variable for end-users.

**Comment by charles-lunarg** [comment]
I went ahead and took your advice - it's nice to tell users that try to enable modules that they can't use them when the platform doesn't support it.
