### ISSUE TITLE
Can't run cmake on Windows 10 with Visual Studio 2017

### ISSUE THREAD

**Issue by Keith-Albright-Bose** [KhronosGroup/Vulkan-Headers#92]
UPDATE: Updated to cmake 3.15.5 and all set.  Please close this issue although you may want to raise the version requirement from 3.10.2 so others don't run afoul of this.

I'm trying to build on Windows as a prereq for the Vulkan Loader.

Following the build instructions:

On version 3.10.2 of CMake.
Cloned latest code
mkdir build
cd build
cmake ..

The default generator comes up correctly as Visual Studio 15 2017.
However,  it errors out:

C:\code\Vulkan-Headers\build>cmake ..
-- Building for: Visual Studio 15 2017
CMake Error at CMakeLists.txt:24 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    The system cannot find the file specified

-- Configuring incomplete, errors occurred!
See also "C:/code/Vulkan-Headers/build/CMakeFiles/CMakeOutput.log".

Not much in log file:
The system is: Windows - 10.0.17134 - AMD64

I did a repair reinstall of VS 2017 but same issue.

**Comment by mark-lunarg** [comment]
When run from a Developer Command Prompt for VS 2017, these steps work seem to work on my Windows machine ( with cmake 3.14.3).

**Comment by mark-lunarg** [comment]
@Keith-Albright-Bose, were you able to get it working?

**Comment by Keith-Albright-Bose** [comment]
Yes, thanks Mark!  Best.

**Comment by mark-lunarg** [comment]
Heh, I looked and nowhere in the build doc did it mention this important detail -- it has since been updated.  Sorry for the trouble!
