### ISSUE TITLE
Move vulkan.hpp to a different repository

### ISSUE THREAD

**Issue by c0d1f1ed** [KhronosGroup/Vulkan-Headers#97]
vulkan.hpp is a whopping 3+ MB file with 75k lines. Some projects use it, while others prefer the bare-bones C interface. As such, while it is technically *a* Vulkan header, it is not an integral part of *the* Vulkan headers. It's not part of the API. The Vulkan spec states "Vulkan is defined as an API in the C99 language", and describes the C headers but there is no mention of vulkan.hpp. Hence it's an optional wrapper and in my opinion doesn't belong in the Vulkan-Headers repo.

The sheer size of the file makes downloads slower (also affecting CI tests), slows down IDEs parsing/indexing it, and when searching through a whole project it produces a lot of false positives when not actually using this header. Hence I suggest moving it to another repo, e.g. Vulkan-Cpp-Headers (note Vulkan-Hpp already contains it, but I understand not all users of vulkan.hpp want all the samples and tests it contains either).

**Comment by oddhack** [comment]
Since you're a Khronos participant I suggest taking this up internally with the main WG call/email, or possibly with the Ecosystem TSG. I don't know all the uses of this repo, but I do know that several downstream repos rely on it for SDK builds and such, so removing anything may have unexpected consequences.

If a couple MB of download are a significant performance hit, the latest C headers could be fetched directly with raw.github.io links. The repo itself is 30+ MB at present and will get bigger, which probably dominates repo clone times.

**Comment by c0d1f1ed** [comment]
I agree we can't do this in one go. To do this thoughtfully I think we need to take the following steps:

1) Create the new repo (e.g. Vulkan-Cpp-Headers).
2a) Update that repo with new vulkan.hpp builds instead of this one.
2b) Update documentation for vulkan.hpp to point to this new repo (ideally simultaneously).
3) Add a #warning to the now forked vulkan.hpp in Vulkan-Headers that it is deprecated and will be removed, why (referencing this issue), and where to find the new version. The warning must have a define to disable it so projects that treat warnings as errors can work around it.
4) Replace the warning with an #error, wich can also be disabled with a define.
5) Remove vulkan.hpp from Vulkan-Headers.

I'll see if our regular call attendants want to discuss this with the working group. If there's agreement that this is a good idea, I can do the work.

**Comment by c0d1f1ed** [comment]
We realized that keeping vulkan.hpp in sync with the C headers would become more complicated if they're in separate repositories. Having a second repo with all the headers except for vulkan.hpp would work, but that would cause confusion and adds maintenance burden for Khronos.

That said, anyone can easily make a clone of the Khronos 
Vulkan-Headers repo on GitHub or elsewhere and remove vulkan.hpp from it and update it at their need (and perhaps put CI in place to check for the absence of vulkan.hpp). So I don't think Khronos involvement is required for this.
